# Generated by Django 5.2.7 on 2026-05-07 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Homeowner', 'Homeowner'), ('Admin', 'Admin'), ('Technician', 'Technician')], default='Homeowner', max_length=20),
        ),
        migrations.AlterField(
            model_name='deviceschedule',
            name='appliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.appliance'),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='energy_consumed',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='DeviceFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='dashboard.appliance')),
            ],
        ),
        migrations.CreateModel(
            name='FaultAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('fault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='dashboard.devicefault')),
                ('technician', models.ForeignKey(limit_choices_to={'profile__role': 'Technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
